### ISSUE TITLE
Turing standard integration

### ISSUE THREAD

**Issue by DominiqueMakowski** [JaimeRZP/MicroCanonicalHMC.jl#13]
Thanks for the package, it looks very interesting! Out of curiosity, are there any potential plans to make it part of the standard Turing library sometime in the future?

**Comment by JaimeRZP** [comment]
Check this tutorial to see Turing integration: https://turinglang.org/docs/tutorials/docs-16-using-turing-external-samplers/index.html

**Comment by DominiqueMakowski** [comment]
Thanks, I guess my question was rather whether this might become someday the "default" non-external Turing sampler ☺️

**Comment by JaimeRZP** [comment]
No worries!
